Profile: BRCoreMedicationRequest
Parent: http://hl7.org/fhir/StructureDefinition/MedicationRequest
Id: br-core-medicationrequest
Title: "br-core-medicationrequest"
Description: "Um pedido ou solicitação para fornecimento do medicamento e instruções para administração do medicamento a um paciente. O recurso é chamado de 'MedicationRequest' em vez de 'MedicationPrescription' ou 'MedicationOrder' para generalizar o uso em ambientes de internação e ambulatorial, incluindo planos de cuidados, etc., e para harmonizar com padrões de fluxo de trabalho"

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso"
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores para este recurso"
* identifier ^definition = "Identificadores para este recurso"
* status ^short = "Status atual da requisição de medicamento: ativa,  em espera, cancelada, concluída, registrada por engano, interrompida, rascunho, desconhecido"
* status ^definition = "Status atual da requisição de medicamento: ativa,  em espera, cancelada, concluída, registrada por engano, interrompida, rascunho, desconhecido"
* statusReason ^short = "Motivo do status atual"
* statusReason ^definition = "Motivo do status atual"
* intent ^short = "Tipo de requisição de medicamento: prescrição, prescrição original, prescrição automática, reposição, refill, planejada, opcional (a critério médico), instância específica da prescrição"
* intent ^definition = "Tipo de requisição de medicamento: prescrição, prescrição original, prescrição automática, reposição, refill, planejada, opcional (a critério médico), instância específica da prescrição"
* category ^short = "Código que identifica a categoria de uso do medicamento requisitado"
* category ^definition = "Código que identifica a categoria de uso do medicamento requisitado"
* priority ^short = "Identifica o grau de prioridade da requisição de medicamentos"
* priority ^definition = "Identifica o grau de prioridade da requisição de medicamentos: rotina | urgente | o mais rápido possível | emergência"
* priority 0..0
* doNotPerform ^short = "Verdadeiro se a requisição for de proibição de execução"
* doNotPerform ^definition = "Verdadeiro se a requisição for de proibição de execução"
* reported[x] ^short = "Informado em vez de registro primário"
* reported[x] ^definition = "Informado em vez de registro primário"
* reportedReference ^short = "Reportado em vez de ser o registro primário"
* reportedReference ^definition = "Reportado em vez de ser o registro primário"
* reportedReference only Reference(br-core-practitioner or br-core-practitionerrole or br-core-patient or br-core-relatedperson or br-core-organization)
* medication[x] ^short = "Medicamento prescrito"
* medication[x] ^definition = "Medicamento prescrito"
* medicationReference ^short = "Referência ao br-core-medication"
* medicationReference ^definition = "Referência ao br-core-medication"
* medicationReference only Reference(br-core-medication)
* subject ^short = "Referência oa paciente que se destina esta requisição de medicamento"
* subject ^definition = "Referência oa paciente que se destina esta requisição de medicamento"
* subject only Reference(br-core-patient)
* subject.id ^short = "Identificador único para referência entre elementos"
* subject.id ^definition = "Identificador único para referência entre elementos"
* subject.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* subject.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* subject.reference ^short = "Referência literal. URL relativa, interna ou externa"
* subject.reference ^definition = "Referência literal. URL relativa, interna ou externa"
* subject.type ^short = "Tipo de recurso ao qual a referência é feita"
* subject.type ^definition = "Tipo de recurso ao qual a referência é feita"
* subject.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* subject.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* subject.display ^short = "Alternativa de texto para o recurso"
* subject.display ^definition = "Alternativa de texto para o recurso"
* encounter ^short = "Referência ao atendimento"
* encounter ^definition = "Referência ao atendimento"
* encounter only Reference(br-core-encounter)
* supportingInformation ^short = "Informações para apoiar a requisição do medicamento"
* supportingInformation ^definition = "Informações para apoiar a requisição do medicamento"
* supportingInformation only Reference(Resource)
* authoredOn ^short = "Data de criação desta requisição de medicamento"
* authoredOn ^definition = "Data de criação desta requisição de medicamento"
* authoredOn 1..1
* requester ^short = "Referência à quem ou o quê solicitou esta requisição"
* requester ^definition = "Referência à quem ou o quê solicitou esta requisição"
* requester 1..1
* requester only Reference(br-core-practitioner or br-core-practitionerrole or br-core-organization or br-core-patient or br-core-relatedperson or Device)
* performer ^short = "Referência ao prescritor indicado para a administração do medicamento"
* performer ^definition = "Referência ao prescritor indicado para a administração do medicamento"
* performer only Reference(br-core-practitioner or br-core-practitionerrole or br-core-organization or br-core-patient or Device or br-core-relatedperson or CareTeam)
* performerType ^short = "Especialidade do prescritor para a administração do medicamento"
* performerType ^definition = "Especialidade do prescritor para a administração do medicamento"
* performerType from https://terminologia.saude.gov.br/fhir/ValueSet/BROcupacao (example)
* recorder ^short = "Pessoa que registrou a requisição"
* recorder ^definition = "Pessoa que registrou a requisição"
* recorder only Reference(br-core-practitioner or br-core-practitionerrole)
* reasonCode ^short = "Motivo ou indicação para solicitar ou não o medicamento. Conceito codificado que indica o motivo pelo qual o medicamento foi solicitado ou não"
* reasonCode ^definition = "Motivo ou indicação para solicitar ou não o medicamento. Conceito codificado que indica o motivo pelo qual o medicamento foi solicitado ou não"
* reasonCode from https://terminologia.saude.gov.br/fhir/ValueSet/BRCID10 (example)
* reasonReference ^short = "Condição ou observação que apoia o motivo pelo qual a prescrição está sendo escrita"
* reasonReference ^definition = "Condição ou observação que apoia o motivo pelo qual a prescrição está sendo escrita"
* reasonReference only Reference(br-core-condition or br-core-observation)
* instantiatesCanonical ^short = "Instancia do protocolo ou definição FHIR"
* instantiatesCanonical ^definition = "Instancia do protocolo ou definição FHIR"
* instantiatesUri ^short = "URI da instancia do  protocolo ou a definição FHIR externa"
* instantiatesUri ^definition = "URI da instancia do protocolo ou a definição externa"
* basedOn ^short = "o quê a requisição atende"
* basedOn ^definition = "o quê a requisição atende"
* basedOn 0..1
* basedOn only Reference(br-core-careplan or br-core-medicationrequest or br-core-servicerequest or ImmunizationRecommendation)
* groupIdentifier ^short = "requisição composta da qual esta requisição faz parte"
* groupIdentifier ^definition = "requisição composta da qual esta requisição faz parte"
* courseOfTherapyType ^short = "Identifica o padrão de administração de medicamentos"
* courseOfTherapyType ^definition = "Identifica o padrão de administração de medicamentos"
* insurance ^short = "Cobertura de planos/seguros de saúde associada"
* insurance ^definition = "Cobertura de planos/seguros de saúde associada"
* insurance only Reference(Coverage or ClaimResponse)
* note ^short = "Informações sobre a requisição"
* note ^definition = "Informações sobre a requisição"
* dosageInstruction ^short = "Como o medicamento deve ser usado"
* dosageInstruction ^definition = "Como o medicamento deve ser usado"
* dosageInstruction 0..1
* dosageInstruction.id ^short = "Identificador exclusivo para referência entre elementos"
* dosageInstruction.id ^definition = "Identificador exclusivo para referência entre elementos"
* dosageInstruction.extension ^short = "Conteúdo adicional definido pelas implementações"
* dosageInstruction.extension ^definition = "Conteúdo adicional definido pelas implementações"
* dosageInstruction.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* dosageInstruction.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* dosageInstruction.sequence ^short = "Ordem na requisição"
* dosageInstruction.sequence ^definition = "Ordem na requisição"
* dosageInstruction.text ^short = "Instruções de dosagem em texto livre, por exemplo, SIG"
* dosageInstruction.text ^definition = "Instruções de dosagem em texto livre, por exemplo, SIG"
* dosageInstruction.additionalInstruction ^short = "Instruções suplementares ou advertências ao paciente"
* dosageInstruction.additionalInstruction ^definition = "Instruções suplementares ou advertências ao paciente - por exemplo: 'com as refeições', 'pode ​​causar sonolência'"
* dosageInstruction.patientInstruction ^short = "Instruções orientadas ao paciente ou ao consumidor"
* dosageInstruction.patientInstruction ^definition = "Instruções orientadas ao paciente ou ao consumidor"
* dosageInstruction.timing ^short = "Quando a medicamento deve ser administrado"
* dosageInstruction.timing ^definition = "Quando a medicamento deve ser administrado"
* dosageInstruction.timing.repeat ^short = "Quando o evento ocorre"
* dosageInstruction.timing.repeat ^definition = "Quando o evento ocorre"
* dosageInstruction.timing.repeat 1..1
//* dosageInstruction.timing.repeat.bounds[x].count ^short = "Número de repetições"
//* dosageInstruction.timing.repeat.bounds[x].count ^definition = "Número de repetições"
//* dosageInstruction.timing.repeat.bounds[x].countMax ^short = "Número de repetições máxima"
//* dosageInstruction.timing.repeat.bounds[x].countMax ^definition = "Número de repetições máxima"
//* dosageInstruction.timing.repeat.bounds[x].duration ^short = "Duração"
//* dosageInstruction.timing.repeat.bounds[x].duration ^definition = "Duração"
//* dosageInstruction.timing.repeat.bounds[x].durationMax ^short = "Duração máxima"
//* dosageInstruction.timing.repeat.bounds[x].durationMax ^definition = "Duração máxima"
//* dosageInstruction.timing.repeat.bounds[x].durationUnit ^short = "unidade da duração: s | min | h | d | se | me | a - unit of time (UCUM)"
//* dosageInstruction.timing.repeat.bounds[x].durationUnit ^definition = "unidade da duração: s | min | h | d | se | me | a - unit of time (UCUM)"
//* dosageInstruction.timing.repeat.bounds[x].frequency ^short = "Frequência por período de tempo"
//* dosageInstruction.timing.repeat.bounds[x].frequency ^definition = "Frequência por período de tempo"
//* dosageInstruction.timing.repeat.bounds[x].frequencyMax ^short = "Frequência máxima por período de tempo"
//* dosageInstruction.timing.repeat.bounds[x].frequencyMax ^definition = "Frequência máxima por período de tempo"
//* dosageInstruction.timing.repeat.bounds[x].period ^short = "Período"
//* dosageInstruction.timing.repeat.bounds[x].period ^definition = "Período"
//* dosageInstruction.timing.repeat.bounds[x].periodMax ^short = "Período máximo"
//* dosageInstruction.timing.repeat.bounds[x].periodMax ^definition = "Período máximo"
//* dosageInstruction.timing.repeat.bounds[x].periodUnit ^short = "unidade do período:s | min | h | d | se | me | a - unit of time (UCUM)"
//* dosageInstruction.timing.repeat.bounds[x].periodUnit ^definition = "unidade do período: s | min | h | d | se | me | a - unit of time (UCUM)"
//* dosageInstruction.timing.repeat.bounds[x].daysOfWeek ^short = "Dias da semana: seg, ter, qua,qui, sex, sab,dom"
//* dosageInstruction.timing.repeat.bounds[x].daysOfWeek ^definition = "Dias da semana: seg, ter, qua,qui, sex, sab,dom"
//* dosageInstruction.timing.repeat.bounds[x].timeOfDay ^short = ""
//* dosageInstruction.timing.repeat.bounds[x].timeOfDay ^definition = "Frequência máxima por período de tempo"
//* dosageInstruction.timing.repeat.bounds[x].period ^short = "Período"
//* dosageInstruction.timing.repeat.bounds[x].period ^definition = "Período"
//* dosageInstruction.timing.repeat.bounds[x].periodMax ^short = "Período máximo"
//* dosageInstruction.timing.repeat.bounds[x].periodMax ^definition = "Período máximo"
//* dosageInstruction.timing.repeat.bounds[x].periodUnit ^short = "unidade do período:s | min | h | d | se | me | a - unit of time (UCUM)"
//* dosageInstruction.timing.repeat.bounds[x].periodUnit ^definition = "unidade do período:s | min | h | d | se | me | a - unit of time (UCUM)"
//* dosageInstruction.timing.repeat.when ^short = "Código para o período de ocorrência"
//* dosageInstruction.timing.repeat.when ^definition = "Código para o período de ocorrência"
//* dosageInstruction.timing.repeat.offset ^short = "Minutos antes ou depois do evento"
//* dosageInstruction.timing.repeat.offset ^definition = "Minutos antes ou depois do evento"
//* dosageInstruction.timing.code ^short = "Abreviatura de tempo"
//* dosageInstruction.timing.code ^definition = "Abreviatura de tempo"
* dosageInstruction.asNeeded[x] ^short = "Conceito codificado que identifica a pré-condição que deve ser atendida ou avaliada antes de consumir ou administrar uma dose de medicamento"
* dosageInstruction.asNeeded[x] ^definition = "Conceito codificado que identifica a pré-condição que deve ser atendida ou avaliada antes de consumir ou administrar uma dose de medicamento"
* dosageInstruction.asNeeded[x] from https://terminologia.saude.gov.br/fhir/ValueSet/BRCID10
* dosageInstruction.site ^short = "Local anatômico de administração do medicamento"
* dosageInstruction.site ^definition = "Local anatômico de administração do medicamento"
* dosageInstruction.route ^short = "Via de admiminstração do medicamento"
* dosageInstruction.route ^definition = "Via de admiminstração do medicamento"
* dosageInstruction.route from http://hl7.org/fhir/uv/ips/ValueSet/medicine-route-of-administration
* dosageInstruction.method ^short = "Método de administração do medicamento"
* dosageInstruction.method ^definition = "Método de administração do medicamento"
* dosageInstruction.doseAndRate ^short = "Quantidade a ser administrada do medicamento"
* dosageInstruction.doseAndRate ^definition = "Quantidade a ser administrada do medicamento"
* dosageInstruction.doseAndRate.id ^short = "Identificador exclusivo para referência entre elementos"
* dosageInstruction.doseAndRate.id ^definition = "Identificador exclusivo para referência entre elementos"
* dosageInstruction.doseAndRate.extension ^short = "Conteúdo adicional definido pelas implementações"
* dosageInstruction.doseAndRate.extension ^definition = "Conteúdo adicional definido pelas implementações"
* dosageInstruction.doseAndRate.type ^short = "O tipo de dose ou taxa de administração especificada"
* dosageInstruction.doseAndRate.type ^definition = "O tipo de dose ou taxa de administração especificada"
* dosageInstruction.doseAndRate.dose[x] ^short = "Quantidade de medicamento por dose"
* dosageInstruction.doseAndRate.dose[x] ^definition = "Quantidade de medicamento por dose"
* dosageInstruction.doseAndRate.dose[x] 1..1
* dosageInstruction.doseAndRate.rate[x] ^short = "Quantidade de medicamento por unidade de tempo"
* dosageInstruction.doseAndRate.rate[x] ^definition = "Quantidade de medicamento por unidade de tempo"
* dosageInstruction.maxDosePerPeriod ^short = "Quantidade máxima de medicamento por unidade de tempo"
* dosageInstruction.maxDosePerPeriod ^definition = "Quantidade máxima de medicamento por unidade de tempo"
* dosageInstruction.maxDosePerAdministration ^short = "Quantidade máxima de medicamento por administração"
* dosageInstruction.maxDosePerAdministration ^definition = "Quantidade máxima de medicamento por administração"
* dosageInstruction.maxDosePerLifetime ^short = "Quantidade máxima de medicamento por toda a vida do paciente"
* dosageInstruction.maxDosePerLifetime ^definition = "Quantidade máxima de medicamento por toda a vida do paciente"
* dispenseRequest ^short = "Autorização de fornecimento de medicamentos"
* dispenseRequest ^definition = "Autorização de fornecimento de medicamentos"
* dispenseRequest.id ^short = "Identificador exclusivo para referência entre elementos"
* dispenseRequest.id ^definition = "Identificador exclusivo para referência entre elementos"
* dispenseRequest.extension ^short = "Conteúdo adicional definido por implementações"
* dispenseRequest.extension ^definition = "Conteúdo adicional definido por implementações"
* dispenseRequest.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* dispenseRequest.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* dispenseRequest.initialFill ^short = "Preenchimento dos primeiros detalhes da autorização de fornecimento de medicamentos"
* dispenseRequest.initialFill ^definition = "Preenchimento dos primeiros detalhes da autorização de fornecimento de medicamentos"
* dispenseRequest.initialFill.id ^short = "Identificador exclusivo para referência entre elementos"
* dispenseRequest.initialFill.id ^definition = "Identificador exclusivo para referência entre elementos"
* dispenseRequest.initialFill.extension ^short = "Conteúdo adicional definido por implementações"
* dispenseRequest.initialFill.extension ^definition = "Conteúdo adicional definido por implementações"
* dispenseRequest.initialFill.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* dispenseRequest.initialFill.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* dispenseRequest.initialFill.quantity ^short = "Quantidade inicial de fornecimento autorizada"
* dispenseRequest.initialFill.quantity ^definition = "Quantidade inicial de fornecimento autorizada"
* dispenseRequest.initialFill.duration ^short = "Duração da primeira autorização de fornecimento de medicamentos"
* dispenseRequest.initialFill.duration ^definition = "Duração da primeira autorização de fornecimento de medicamentos"
* dispenseRequest.dispenseInterval ^short = "Período mínimo de tempo entre dispensações de medicamentos autorizado"
* dispenseRequest.dispenseInterval ^definition = "Período mínimo de tempo entre dispensações de medicamentos autorizado"
* dispenseRequest.validityPeriod ^short = "Validade da autorização de fornecimento de medicamentos"
* dispenseRequest.validityPeriod ^definition = "validade da autorização de fornecimento de medicamentos"
* dispenseRequest.validityPeriod 1..1
* dispenseRequest.validityPeriod.id ^short = "Identificador exclusivo para referência entre elementos"
* dispenseRequest.validityPeriod.id ^definition = "Identificador exclusivo para referência entre elementos"
* dispenseRequest.validityPeriod.start ^short = "Data/Hora do início da validade da autorização(intervalo fechado)"
* dispenseRequest.validityPeriod.start ^definition = "Data/Hora de início da validade da autorização (intervalo fechado)"
* dispenseRequest.validityPeriod.end ^short = "Data/Hora do final da validade da autorização(intervalo fechado)"
* dispenseRequest.validityPeriod.end ^definition = "Data/Hora do final da validade da autorização(intervalo fechado), se não for contínuo"
* dispenseRequest.numberOfRepeatsAllowed ^short = "Número de refills autorizados"
* dispenseRequest.numberOfRepeatsAllowed ^definition = "Número de refills autorizados"
* dispenseRequest.quantity ^short = "Quantidade de medicamento a ser fornecido por dispensação"
* dispenseRequest.quantity ^definition = "Quantidade de medicamento a ser fornecido por dispensação"
* dispenseRequest.expectedSupplyDuration ^short = "Número de dias de fornecimento de medicamentos por dispensação"
* dispenseRequest.expectedSupplyDuration ^definition = "Número de dias de fornecimento de medicamentos por dispensação"
* dispenseRequest.performer ^short = "Referência à organização preferencial para a dispensação"
* dispenseRequest.performer ^definition = "Referência à organização preferencial para a dispensação"
* dispenseRequest.performer only Reference(br-core-organization)
* substitution ^short = "Restrições à substituição de medicamentos"
* substitution ^definition = "Restrições à substituição de medicamentos"
* substitution.id ^short = "Identificador exclusivo para referência entre elementos"
* substitution.id ^definition = "Identificador exclusivo para referência entre elementos"
* substitution.extension ^short = "Conteúdo adicional definido por implementações"
* substitution.extension ^definition = "Conteúdo adicional definido por implementações"
* substitution.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* substitution.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* substitution.allowed[x] ^short = "Informa se a substituição de medicamentos é ou não permitida"
* substitution.allowed[x] ^definition = "Informa se a substituição de medicamentos é ou não permitida"
* substitution.reason ^short = "Porque (ou não) a substituição foi feita"
* substitution.reason ^definition = "Um conceito codificado que descreve a razão pela qual um medicamento diferente deve (ou não) ser substituído daquele que foi prescrito"
* priorPrescription ^short = "Referência à requisição anterior que está sendo substituída"
* priorPrescription ^definition = "Referência à requisição anterior que está sendo substituída"
* priorPrescription only Reference(br-core-medicationrequest)
* detectedIssue ^short = "Referência à condição clínica detectada"
* detectedIssue ^definition = "Referência à condição clínica detectada"
* detectedIssue only Reference(DetectedIssue)
* eventHistory ^short = "Referência à uma lista de eventos de interesse na linha do tempo"
* eventHistory ^definition = "Referência à uma lista de eventos de interesse na linha do tempo"
* eventHistory only Reference(Provenance)
